### ISSUE TITLE
Lock title persistently even when restarting Chrome?

### ISSUE THREAD

**Issue by orschiro** [imsut/locktitle#1]
Hey @imsut 

really like this extension idea!

One thing I noticed is that changes to the title are not persistent across restarting Chrome.

Is this something that can be achieved?

**Comment by imsut** [comment]
Thx for the comment!
This project is, unfortunately, not under active development.
That said, I *think* it's possible to store tab-name mapping and restore it on Chrome startup.

**Comment by orschiro** [comment]
> That said, I think it's possible to store tab-name mapping and restore it on Chrome startup.

Thanks @imsut! Something you may want to implement or disregard since not under active development?

**Comment by imsut** [comment]
the feature sounds great. PR would be welcomed!

**Comment by imsut** [comment]
the feature sounds great. PR would be welcomed.

**Comment by imsut** [comment]
sorry. closed this issue by mistake. I don't seem to be able to re-open. please do if you can.

**Comment by orschiro** [comment]
> the feature sounds great. PR would be welcomed.

Will see what I can do!
